CREATE TABLE articles (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY COMMENT '記事ID',
    title VARCHAR(255) NOT NULL COMMENT 'タイトル',
    content TEXT NOT NULL COMMENT '本文',
    author VARCHAR(64) NOT NULL COMMENT '著者',
    created TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '記事作成日時',
    updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '記事更新日時',
    UNIQUE KEY (author, title) USING BTREE
) COMMENT='記事テーブル';
